#define CPU_x0 16 /* __builtin_offsetof(struct cpu_state, x0) */
#define CPU_x1 24 /* __builtin_offsetof(struct cpu_state, x1) */
#define CPU_x2 32 /* __builtin_offsetof(struct cpu_state, x2) */
#define CPU_x3 40 /* __builtin_offsetof(struct cpu_state, x3) */
#define CPU_x4 48 /* __builtin_offsetof(struct cpu_state, x4) */
#define CPU_x5 56 /* __builtin_offsetof(struct cpu_state, x5) */
#define CPU_x6 64 /* __builtin_offsetof(struct cpu_state, x6) */
#define CPU_x7 72 /* __builtin_offsetof(struct cpu_state, x7) */
#define CPU_x8 80 /* __builtin_offsetof(struct cpu_state, x8) */
#define CPU_x9 88 /* __builtin_offsetof(struct cpu_state, x9) */
#define CPU_x10 96 /* __builtin_offsetof(struct cpu_state, x10) */
#define CPU_x11 104 /* __builtin_offsetof(struct cpu_state, x11) */
#define CPU_x12 112 /* __builtin_offsetof(struct cpu_state, x12) */
#define CPU_x13 120 /* __builtin_offsetof(struct cpu_state, x13) */
#define CPU_x14 128 /* __builtin_offsetof(struct cpu_state, x14) */
#define CPU_x15 136 /* __builtin_offsetof(struct cpu_state, x15) */
#define CPU_x16 144 /* __builtin_offsetof(struct cpu_state, x16) */
#define CPU_x17 152 /* __builtin_offsetof(struct cpu_state, x17) */
#define CPU_x18 160 /* __builtin_offsetof(struct cpu_state, x18) */
#define CPU_x19 168 /* __builtin_offsetof(struct cpu_state, x19) */
#define CPU_x20 176 /* __builtin_offsetof(struct cpu_state, x20) */
#define CPU_x21 184 /* __builtin_offsetof(struct cpu_state, x21) */
#define CPU_x22 192 /* __builtin_offsetof(struct cpu_state, x22) */
#define CPU_x23 200 /* __builtin_offsetof(struct cpu_state, x23) */
#define CPU_x24 208 /* __builtin_offsetof(struct cpu_state, x24) */
#define CPU_x25 216 /* __builtin_offsetof(struct cpu_state, x25) */
#define CPU_x26 224 /* __builtin_offsetof(struct cpu_state, x26) */
#define CPU_x27 232 /* __builtin_offsetof(struct cpu_state, x27) */
#define CPU_x28 240 /* __builtin_offsetof(struct cpu_state, x28) */
#define CPU_x29 248 /* __builtin_offsetof(struct cpu_state, x29) */
#define CPU_x30 256 /* __builtin_offsetof(struct cpu_state, x30) */
#define CPU_sp 264 /* __builtin_offsetof(struct cpu_state, sp) */
#define CPU_pc 272 /* __builtin_offsetof(struct cpu_state, pc) */
#define CPU_tls_ptr 808 /* __builtin_offsetof(struct cpu_state, tls_ptr) */
#define CPU_nf 280 /* __builtin_offsetof(struct cpu_state, nf) */
#define CPU_zf 281 /* __builtin_offsetof(struct cpu_state, zf) */
#define CPU_cf 282 /* __builtin_offsetof(struct cpu_state, cf) */
#define CPU_vf 283 /* __builtin_offsetof(struct cpu_state, vf) */
#define CPU_nzcv 284 /* __builtin_offsetof(struct cpu_state, nzcv) */
#define CPU_fp 288 /* __builtin_offsetof(struct cpu_state, fp) */
#define CPU_fpcr 800 /* __builtin_offsetof(struct cpu_state, fpcr) */
#define CPU_fpsr 804 /* __builtin_offsetof(struct cpu_state, fpsr) */
#define CPU_excl_addr 816 /* __builtin_offsetof(struct cpu_state, excl_addr) */
#define CPU_excl_val 824 /* __builtin_offsetof(struct cpu_state, excl_val) */
#define CPU_excl_val2 832 /* __builtin_offsetof(struct cpu_state, excl_val2) */
#define CPU_cycle 8 /* __builtin_offsetof(struct cpu_state, cycle) */
#define LOCAL_bp 880 /* __builtin_offsetof(struct fiber_frame, bp) */
#define LOCAL_value 896 /* __builtin_offsetof(struct fiber_frame, value) */
#define LOCAL_value_addr 888 /* __builtin_offsetof(struct fiber_frame, value_addr) */
#define LOCAL_last_block 928 /* __builtin_offsetof(struct fiber_frame, last_block) */
#define LOCAL_jit_exit_sp 936 /* __builtin_offsetof(struct fiber_frame, jit_exit_sp) */
#define LOCAL_ret_cache 944 /* __builtin_offsetof(struct fiber_frame, ret_cache) */
#define CPU_segfault_addr 840 /* __builtin_offsetof(struct cpu_state, segfault_addr) */
#define CPU_segfault_was_write 848 /* __builtin_offsetof(struct cpu_state, segfault_was_write) */
#define CPU_poked_ptr 856 /* __builtin_offsetof(struct cpu_state, poked_ptr) */
#define CPU_cycle 8 /* __builtin_offsetof(struct cpu_state, cycle) */
#define MEM_READ 0 /* 0 */
#define MEM_WRITE 1 /* 1 */
#define FIBER_BLOCK_addr 0 /* __builtin_offsetof(struct fiber_block, addr) */
#define FIBER_BLOCK_code 192 /* __builtin_offsetof(struct fiber_block, code) */
#define TLB_entries 32 /* __builtin_offsetof(struct tlb, entries) */
#define TLB_mmu 0 /* __builtin_offsetof(struct tlb, mmu) */
#define TLB_dirty_page 8 /* __builtin_offsetof(struct tlb, dirty_page) */
#define TLB_segfault_addr 24 /* __builtin_offsetof(struct tlb, segfault_addr) */
#define TLB_block_cache 262176 /* __builtin_offsetof(struct tlb, block_cache) */
#define TLB_block_cache_gen 294944 /* __builtin_offsetof(struct tlb, block_cache_gen) */
#define TLB_ENTRY_page 0 /* __builtin_offsetof(struct tlb_entry, page) */
#define TLB_ENTRY_page_if_writable 8 /* __builtin_offsetof(struct tlb_entry, page_if_writable) */
#define TLB_ENTRY_data_minus_addr 16 /* __builtin_offsetof(struct tlb_entry, data_minus_addr) */
#define TLB_ENTRY_gen 24 /* __builtin_offsetof(struct tlb_entry, gen) */
#define MMU_changes 16 /* __builtin_offsetof(struct mmu, changes) */
